import "../style/globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/navigation/header";
import Footer from "@/components/navigation/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${inter.className} bg-gray-100`}>
        <Header />
        <main className="absolute inset-x-10 lg:inset-x-28 mt-36">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
