import "../style/globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/navigation/header";
import Footer from "@/components/navigation/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${inter.className}`}
      >
        <div className="flex flex-col bg-gray-100 min-h-screen">
          <Header />
          <main className="flex-grow">
            <div className="container mx-auto">{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
